config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => 'homes#about'
  resources :users
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,  length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name,  length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction,  length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book= Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books= Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books= Book.all
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if@book.update(book_params)
     redirect_to book_path(@book.id), notice:"You have created book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(book_params)
     @user.save
    redirect_to usr_path(user.id)
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
     redirect_to user_path(@user.id), notice:"You have updated user successfully."
    else
     render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">



  		<h1>Editing Book</h1>

  		 <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <li>
            <% @book.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
            </li>
          </ul>
        <% end %>
      </div>


  		<%= form_with model: @book, url:book_path, local:true do |f| %>
  		<div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_title">Opinion</label>
        <%= f.text_area :body, class:"form-control book_title" %>
      </div>
      <div class="form-group">
      <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>
      <a><%=link_to "Show", book_path %></a> | <a><%=link_to "Back", books_path %></a>
  	</div>
  </div>
  </div>
  </p>
  </main>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

    <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> error prohibited this obj from being saved:
          <ul>
            <li>
            <% @book.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
            </li>
          </ul>
        <% end %>
      </div>

  <div class="row">
    <div class="col-md-3">



  <h2>User info</h2>

  <table class="table table-hover table-inverse">
    <tr><%= attachment_image_tag current_user, :profile_image, :fill, 63, 63, fallback: "NO_IMAGE.jpeg", size:'63x63' %></tr>
    <tr>
	   <th>name</th>
	   <th><%= current_user.name %></th>
    </tr>
    <tr>
     <th>introduction</th>
     <th><%= current_user.introduction %></th>
    </tr>
  </table>

  <div class="row">
    <%=link_to "", edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %></a>
  </div>


  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book, url:books_path, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>opionion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

    </div>



  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
　 <table class="table table-hover table-inverse">
　 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
　 <% @books.each do |book|%>
　 <tr>
　  <td><span>
　  <%=link_to user_path(book.user_id) do %>
　  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
　  <% end %>
　  </span></td>
  　<td><span><%=link_to book.title,book_path(book)%></span></td>
 　  <td><span><%=book.body%></span></td>
　 </tr>
　<%end%>
　</tbody>

　</table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

     <h2>User info</h2>

      <table class="table table-hover table-inverse">
       <tr>
        <%=link_to user_path(@book.user) do %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 63, 63, fallback: "NO_IMAGE.jpeg", size:'63x63' %>
        <% end %>
        </tr>
       <tr>
	      <th>name</th>
	      <th><%= @book.user.name %></th>
       </tr>
       <tr>
        <th>introduction</th>
        <th><%= @book.user.introduction %></th>
       </tr>
       </table>


    <div class="row">
     <%=link_to "", edit_user_path(@book.user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %></a>
    </div>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @newbook, url:books_path, local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>opionion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>

    </div>

  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
  <tbody>
  <tr>
　 <tbody>
　 <tr>
　  <td><span><%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></span><br>
　  <%=link_to @book.user.name, user_path(@book.user) %></td>
  　<td><span><%=link_to @book.title,book_path(@book)%></span></td>
 　  <td><span><%=@book.body%></span></td>
 　<% if @book.user == current_user %>
 　<td><span><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></span>
 　</td>
 　 <td><span><%= link_to" Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger" %></span></td>
 　<%end%>
　</tr>
　</tbody>
  </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
         <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
         <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
    </div>
  </div>
  </div>

</main>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
　<body>

    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
              <%= link_to "Home", user_path(current_user),  class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Users", user_registration_path,  class: 'fas fa-users nav-link text-light' %>
            </li>
             <li class="nav-item">
              <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
             <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


   <%= render 'layouts/notifications' %>
   <%= yield %>




<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <div id="error_explanation">
        <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <li><% @user.errors.full_messages.each do |message| %>
          <%= message %>
          <% end %>
          </li>
        </ul>
        <% end %>
      </div>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前",class: "form-control name"%>
        </div>
        <div class="form-group">
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60%>
        <label for="inputImage">ProfileImage</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" ,class: "form-control-file user_image"%>
        </div>
        <div class="form-group">
        <label for="inputName">introduction</label>
        <%= f.text_area :introduction,class: "form-control introduction" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

  <h2>User info</h2>

  <table class="table table-hover table-inverse">
    <tr><%= attachment_image_tag current_user, :profile_image, :fill, 63, 63, fallback: "NO_IMAGE.jpeg", size:'63x63' %></tr>
    <tr>
	   <th>name</th>
	   <th><%= current_user.name %></th>
    </tr>
    <tr>
     <th>introduction</th>
     <th><%= current_user.introduction %></th>
    </tr>
  </table>

  <div class="row">
    <%=link_to "", edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %></a>
  </div>


  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book, url:books_path, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>opionion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

    </div>



 <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
　 <table class="table table-hover table-inverse">
　 <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
　 <% @users.each do |user|%>
　 <tr>
　  <td><span><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></span></td>
  　<td><span><%= user.name %></span></td>
 　  <td><span><%= link_to "Show", user_path(user) %></span></td>
　 </tr>
　<%end%>

　</table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>